baseURL: "https://bnpersson.github.io" 
title: Björn Persson
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Visualizations
          url: visualizations/
          weight: 5

params:
    description: "This website hosts Björn Persson's research papers, courses, data, curriculum vitae, and contact information."
    author: Björn Persson
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Björn N. Persson, PhD
          subtitle: "I'm a postdoctoral researcher at Karolinska Institutet, Sweden. My work is in psychology, focusing on individual differences and sex differences in cognition, personality and interests. My PhD <a href='https://www.utupub.fi/bitstream/handle/10024/148451/AnnalesB496Persson.pdf?sequence=1'>thesis</a> was about the \"Dark Triad\", or perhaps more accurately, three variants of antagonistic personality traits. While I have put the Dark Triad behind me, specifically, I'm still interested in psychopathology, especially the distinction between normal and abnormal personality traits.<br><br>This page functions as both a portfolio of sorts and a place where I can upload various things I'd like to save or may want to share. Like many others, I've been inspired by Kristoffer Magnusson (<a href='https://www.rpsychologist.com'>www.rpsychologist.com</a>), in particular his visualizations. These days, AI makes it possible to create similar interactive visualizations without being a strong programmer, which is definitely more my lane."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Visualizations
              url: visualizations/

    socialIcons:
        - name: CV
          url: bnp_cv.pdf
        - name: Email
          url: mailto:persson.jb@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=SiCYagsAAAAJ

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: false
    label:
      text: "Björn Persson"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2